def streaming_setup_html():
    parts = [r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SurroundCore Streaming</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:#111;color:#eee}
main{max-width:980px;margin:auto;padding:28px}.card{background:#1d1d1f;border-radius:14px;padding:18px;margin:14px 0}
h1,h2{margin:.2em 0}.muted{color:#aaa}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}
button,input,select{font:inherit;padding:9px 11px;border-radius:9px;border:1px solid #555;background:#29292b;color:#fff}
button{cursor:pointer}.ok{color:#73d17c}.warn{color:#f0c66b}.bad{color:#ff7777}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.provider{border:1px solid #38383b;border-radius:12px;padding:14px}.provider h3{margin:0 0 7px}.pill{font-size:.8em;padding:3px 7px;border-radius:99px;background:#333}
label{display:flex;justify-content:space-between;gap:15px;margin:9px 0}code{color:#9dd7ff}
</style></head><body><main>
<h1>SurroundCore Streaming</h1>
<p class="muted">Accounts, source quality and native streaming live on the Core. ControlMac remains a controller.</p>
<div class="card" id="login"><h2>Core access</h2><div class="row"><input id="token" type="password" placeholder="SurroundCore token"><button onclick="connect()">Connect</button></div><p id="authstate" class="muted">Enter the Core token once for this browser session.</p></div>
<div id="app" hidden>
<div class="card"><h2>Quality policy</h2><p class="muted">Highest native resolution first. No downsample or downmix unless explicitly enabled.</p>
<div id="quality"></div></div>
<div class="card"><h2>Streaming services</h2><div id="providers" class="grid"></div></div>
''']
    parts.append(r'''
<div class="card"><h2>Spotify</h2>
<p class="muted">Uses the official Spotify Soloist daemon on the Core. Premium can use Spotify Lossless up to 24-bit/44.1 kHz.</p>
<div class="row"><input id="spKey" type="password" placeholder="Soloist API key"><input id="spName" value="SurroundCore Spotify" placeholder="Connect device name"><input id="spWs" value="127.0.0.1:9090" placeholder="Soloist WebSocket"><button onclick="saveSpotify()">Save</button><button onclick="spotifyStatus()">Status</button></div>
<div class="row"><input id="spUri" size="42" placeholder="spotify:album:… or spotify:track:…"><button onclick="spotifyPlay()">Play URI</button><button onclick="spotifyCmd('pause')">Pause</button><button onclick="spotifyCmd('previous')">Previous</button><button onclick="spotifyCmd('next')">Next</button></div><div id="spotifyState" class="muted"></div></div>
<div class="card"><h2>Sonos Radio / Favorites</h2>
<p class="muted">Uses Sonos OAuth and the official Control API. Sonos Radio stays on Sonos hardware.</p>
<div class="row"><input id="soClient" placeholder="Sonos client ID"><input id="soSecret" type="password" placeholder="Sonos client secret"><input id="soRedirect" size="38" placeholder="https://your-public-callback.example/sonos"><button onclick="saveSonos()">Save</button><button onclick="sonosLogin()">Login with Sonos</button></div>
<div class="row"><input id="soCode" placeholder="Authorization code"><button onclick="sonosExchange()">Exchange code</button><button onclick="loadSonos()">Load Favorites</button></div><div id="sonosState" class="muted"></div><div id="sonosFavorites"></div></div>
<div class="card"><h2>Licensed / partner streaming modules</h2>
<p class="muted">TIDAL, Qobuz, HDtracks/AIRIA, Apple Music and Audible plug into a local authorised provider module. SurroundCore always requests highest-native / lossless-first.</p>
<div class="row"><select id="brProvider"><option value="tidal">TIDAL</option><option value="qobuz">Qobuz</option><option value="hdtracks">HDtracks / AIRIA</option><option value="apple_music">Apple Music</option><option value="audible">Audible</option></select><input id="brUrl" size="34" placeholder="Local authorised module URL"><input id="brClient" placeholder="Client ID / app ID"><input id="brSecret" type="password" placeholder="Client secret"><input id="brToken" type="password" placeholder="Access token (optional)"><button onclick="saveBridge()">Save</button><button onclick="bridgeStatus()">Status</button></div>
<div class="row"><input id="brSearch" placeholder="Search provider"><button onclick="bridgeSearch()">Search</button></div><div id="bridgeState" class="muted"></div><div id="bridgeResults"></div></div>
<div class="card"><h2>Bandcamp</h2>
<p class="muted">Use the Subsonic credentials generated in Bandcamp Fan Settings. Credentials stay on SurroundCore.</p>
<div class="row"><input id="bcServer" size="34" value="https://bandcamp.com/api/subsonic"><input id="bcUser" placeholder="Bandcamp Subsonic username"><input id="bcPass" type="password" placeholder="Bandcamp Subsonic password"><button onclick="saveBandcamp()">Test & Save</button><button onclick="disconnectBandcamp()">Disconnect</button><button onclick="loadBandcampAlbums()">Browse purchases</button></div>
<div id="bandcampState" class="muted"></div><div id="bandcampLibrary"></div></div>
<div class="card"><h2>Podcasts / RSS</h2>
<div class="row"><input id="podName" placeholder="Optional name"><input id="podUrl" size="44" placeholder="https://example.com/feed.xml"><button onclick="addPodcast()">Add feed</button></div>
<div id="podcasts"></div></div>
<div class="card"><h2>Internet Radio</h2>
<div class="row"><input id="stationName" placeholder="Station name"><input id="stationUrl" size="42" placeholder="https://stream.example/radio"><button onclick="addStation()">Add station</button></div>
<div id="stations"></div></div>
</div>
<script>
let TOKEN=sessionStorage.getItem('surroundcore-token')||'';let ENDPOINTS=[];
const auth=()=>({'Authorization':'Bearer '+TOKEN,'Content-Type':'application/json'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const endpointOptions=()=>ENDPOINTS.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('');
function hashToken(){if(location.hash.startsWith('#token=')){TOKEN=decodeURIComponent(location.hash.slice(7));sessionStorage.setItem('surroundcore-token',TOKEN);history.replaceState(null,'',location.pathname+location.search)}}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),...auth()};let r=await fetch(path,opt);if(!r.ok)throw new Error(await r.text());return await r.json()}
async function connect(){TOKEN=document.getElementById('token').value||TOKEN;if(!TOKEN)return;sessionStorage.setItem('surroundcore-token',TOKEN);try{await load();document.getElementById('app').hidden=false;document.getElementById('authstate').textContent='Connected';document.getElementById('authstate').className='ok'}catch(e){document.getElementById('authstate').textContent='Connection failed';document.getElementById('authstate').className='bad'}}
async function load(){let [d,e]=await Promise.all([api('/api/v1/streaming'),api('/api/v1/endpoints')]);ENDPOINTS=(e.endpoints||[]).filter(x=>x.address&&(x.kind==='alsa'||x.kind==='meridian'));renderQuality(d.quality);renderProviders(d.providers);renderStations(d.settings.radio_stations||[]);renderPodcastFeeds(d.settings.podcast_feeds||[]);loadBandcampStatus()}
function renderQuality(q){let a=q.airia_available?'available':'licensed module not installed';document.getElementById('quality').innerHTML=`<p><b>Source:</b> highest native · <b>AIRIA:</b> ${a} · <b>MQA:</b> pass-through ${q.mqa_passthrough?'on':'off'} · <b>Output:</b> ${q.output_transport}</p><p class="muted">MHR/MMHR are only selected when a Meridian endpoint genuinely advertises the transport.</p>`}
''')
    parts.append(r'''
function renderProviders(items){let box=document.getElementById('providers');box.innerHTML='';for(const p of items){let state=p.implemented?'<span class="ok">Core module ready</span>':'<span class="warn">Official integration/partner module pending</span>';let cfg=p.configured?'<br><span class="warn">Credentials/config saved</span>':'';let conn=p.connected?'<br><span class="ok">Account authorised</span>':'';let air=p.airia_available===undefined?'':`<br>AIRIA: ${p.airia_available?'available':'licensed module required'}`;let solo=p.soloist_available===undefined?'':`<br>Spotify Soloist: ${p.soloist_available?'installed':'install from Spotify Developer'}`;box.insertAdjacentHTML('beforeend',`<div class="provider"><h3>${p.name}</h3><span class="pill">${p.kind}</span><p>${state}${cfg}${conn}</p><p class="muted">Auth: ${p.auth}<br>Quality: ${p.quality}<br>${(p.formats||[]).join(' · ')}${air}${solo}</p></div>`)}}

async function saveSpotify(){let api_key=document.getElementById('spKey').value,device_name=document.getElementById('spName').value.trim()||'SurroundCore Spotify',ws=document.getElementById('spWs').value.trim()||'127.0.0.1:9090';if(!api_key)return;let d=await api('/api/v1/providers/spotify/configure',{method:'POST',body:JSON.stringify({api_key,binary:'/opt/spotify/soloist',device_name,ws,data_dir:'/data/spotify'})});document.getElementById('spKey').value='';document.getElementById('spotifyState').textContent=d.binary_available?'Configured · Soloist binary available':'Configured · install/mount official Soloist binary';await load()}
async function spotifyStatus(){try{let d=await api('/api/v1/providers/spotify');document.getElementById('spotifyState').textContent=JSON.stringify(d.runtime||d.runtime_error||d)}catch(e){document.getElementById('spotifyState').textContent=e.message}}
async function spotifyPlay(){let uri=document.getElementById('spUri').value.trim();try{await api('/api/v1/providers/spotify/play',{method:'POST',body:JSON.stringify({uri:uri||null})});spotifyStatus()}catch(e){document.getElementById('spotifyState').textContent=e.message}}
async function spotifyCmd(c){try{await api('/api/v1/providers/spotify/'+encodeURIComponent(c),{method:'POST'});spotifyStatus()}catch(e){document.getElementById('spotifyState').textContent=e.message}}

async function saveSonos(){let client_id=document.getElementById('soClient').value.trim(),client_secret=document.getElementById('soSecret').value,redirect_uri=document.getElementById('soRedirect').value.trim();if(!client_id||!client_secret||!redirect_uri)return;let d=await api('/api/v1/providers/sonos/configure',{method:'POST',body:JSON.stringify({client_id,client_secret,redirect_uri})});document.getElementById('soSecret').value='';document.getElementById('sonosState').textContent=d.configured?'Sonos developer credentials saved':'Sonos not configured';await load()}
async function sonosLogin(){try{let d=await api('/api/v1/providers/sonos/authorize-url');window.open(d.url,'_blank','noopener');document.getElementById('sonosState').textContent='Complete Sonos login, then paste the returned authorization code below.'}catch(e){document.getElementById('sonosState').textContent=e.message}}
async function sonosExchange(){let code=document.getElementById('soCode').value.trim();if(!code)return;try{let d=await api('/api/v1/providers/sonos/exchange-code',{method:'POST',body:JSON.stringify({code})});document.getElementById('soCode').value='';document.getElementById('sonosState').textContent=d.authorised?'Sonos authorised':'Authorization incomplete';await loadSonos()}catch(e){document.getElementById('sonosState').textContent=e.message}}
async function loadSonos(){let box=document.getElementById('sonosFavorites');box.textContent='Loading Sonos households…';try{let hs=(await api('/api/v1/providers/sonos/households')).households||[];box.innerHTML='';for(const h of hs){let hid=h.id||h.householdId;let gd=await api('/api/v1/providers/sonos/households/'+encodeURIComponent(hid)+'/groups'),fd=await api('/api/v1/providers/sonos/households/'+encodeURIComponent(hid)+'/favorites');let groups=gd.groups||[],favs=fd.items||fd.favorites||fd.favoriteList||[];let wrap=document.createElement('div');wrap.innerHTML=`<h3>${esc(h.name||hid)}</h3>`;for(const f of favs){let row=document.createElement('div');row.className='row';row.style.marginTop='7px';let fid=f.id||f.favoriteId,name=f.name||f.title||fid;row.innerHTML=`<span>${esc(name)}</span><span class="muted">${esc((f.service||{}).name||'Sonos Favorite')}</span><select>${groups.map(g=>`<option value="${esc(g.id)}">${esc(g.name||g.id)}</option>`).join('')}</select><button>Play</button>`;let sel=row.querySelector('select');row.querySelector('button').onclick=()=>sonosPlayFavorite(fid,sel.value);wrap.appendChild(row)}box.appendChild(wrap)}}catch(e){box.textContent='Sonos load failed: '+e.message}}
async function sonosPlayFavorite(fid,gid){if(!fid||!gid)return;try{await api('/api/v1/providers/sonos/favorite',{method:'POST',body:JSON.stringify({favorite_id:String(fid),group_id:String(gid)})});document.getElementById('sonosState').textContent='Playing Sonos favorite'}catch(e){document.getElementById('sonosState').textContent=e.message}}

async function saveBridge(){let provider=document.getElementById('brProvider').value,base_url=document.getElementById('brUrl').value.trim(),client_id=document.getElementById('brClient').value.trim(),client_secret=document.getElementById('brSecret').value,access_token=document.getElementById('brToken').value;if(!base_url)return;let d=await api('/api/v1/providers/bridge/'+encodeURIComponent(provider)+'/configure',{method:'POST',body:JSON.stringify({base_url,client_id:client_id||null,client_secret:client_secret||null,access_token:access_token||null})});document.getElementById('brSecret').value='';document.getElementById('brToken').value='';document.getElementById('bridgeState').textContent=d.configured?provider+' bridge configured':provider+' not configured';await load()}
async function bridgeStatus(){let provider=document.getElementById('brProvider').value;try{let d=await api('/api/v1/providers/bridge/'+encodeURIComponent(provider));document.getElementById('bridgeState').textContent=d.available?'Module online · highest native':'Configured but module offline/not installed: '+(d.runtime_error||'')}catch(e){document.getElementById('bridgeState').textContent=e.message}}
async function bridgeSearch(){let provider=document.getElementById('brProvider').value,q=document.getElementById('brSearch').value.trim(),box=document.getElementById('bridgeResults');if(!q)return;box.textContent='Searching…';try{let d=await api('/api/v1/providers/bridge/'+encodeURIComponent(provider)+'/search?q='+encodeURIComponent(q));let items=d.items||d.results||[];box.innerHTML='';for(const item of items){let row=document.createElement('div');row.className='row';row.style.marginTop='6px';let id=item.id||item.uri,name=item.name||item.title||id;row.innerHTML=`<span>${esc(name)}</span><span class="muted">${esc(item.quality||item.format||'highest available')}</span><button>Play highest</button>`;row.querySelector('button').onclick=()=>bridgePlay(provider,id);box.appendChild(row)}}catch(e){box.textContent=e.message}}
async function bridgePlay(provider,id){try{await api('/api/v1/providers/bridge/'+encodeURIComponent(provider)+'/play',{method:'POST',body:JSON.stringify({item_id:String(id),endpoint_id:null})});document.getElementById('bridgeState').textContent='Provider accepted highest-quality playback request'}catch(e){document.getElementById('bridgeState').textContent=e.message}}

async function loadBandcampStatus(){try{let d=await api('/api/v1/providers/bandcamp');document.getElementById('bandcampState').textContent=d.configured?`Connected as ${d.username}`:'Not connected';if(d.server)document.getElementById('bcServer').value=d.server;if(d.username)document.getElementById('bcUser').value=d.username}catch(e){document.getElementById('bandcampState').textContent='Bandcamp status unavailable'}}
async function saveBandcamp(){let server=document.getElementById('bcServer').value.trim(),username=document.getElementById('bcUser').value.trim(),password=document.getElementById('bcPass').value;if(!username||!password)return;let b=document.getElementById('bandcampState');b.textContent='Testing Bandcamp…';try{let d=await api('/api/v1/providers/bandcamp/configure',{method:'POST',body:JSON.stringify({server,username,password})});b.textContent=`Connected as ${d.account.username}`;document.getElementById('bcPass').value='';await load()}catch(e){b.textContent='Bandcamp login failed: '+e.message}}
async function disconnectBandcamp(){await api('/api/v1/providers/bandcamp/configure',{method:'DELETE'});document.getElementById('bandcampState').textContent='Disconnected';document.getElementById('bandcampLibrary').innerHTML='';await load()}
async function loadBandcampAlbums(){let box=document.getElementById('bandcampLibrary');box.textContent='Loading purchases…';try{let d=await api('/api/v1/providers/bandcamp/albums?size=200');box.innerHTML='';for(const a of d.albums||[]){let row=document.createElement('div');row.className='row';row.style.marginTop='8px';let id=encodeURIComponent(a.id||'');row.innerHTML=`<b>${esc(a.artist||'')}</b><span>${esc(a.name||a.title||'Album')}</span><button>Open</button>`;row.querySelector('button').onclick=()=>openBandcampAlbum(id);box.appendChild(row)}}catch(e){box.textContent='Bandcamp browse failed: '+e.message}}
async function openBandcampAlbum(encodedId){let box=document.getElementById('bandcampLibrary');let d=await api('/api/v1/providers/bandcamp/albums/'+encodedId),a=d.album||{};box.innerHTML=`<h3>${esc(a.artist||'')} — ${esc(a.name||a.title||'Album')}</h3>`;let i=0;for(const t of a.song||[]){let n=i++,row=document.createElement('div');row.className='row';row.style.marginTop='7px';row.innerHTML=`<span>${esc(t.track||'')} ${esc(t.title||'Track')}</span><span class="muted">${esc(t.suffix||t.contentType||'')}</span><select>${endpointOptions()}</select><button>Play</button>`;let sel=row.querySelector('select');row.querySelector('button').onclick=()=>playBandcamp(t.id,sel);box.appendChild(row)}}
async function playBandcamp(songId,sel){if(!sel.value){alert('No playable endpoint is registered');return}await api('/api/v1/streaming/play',{method:'POST',body:JSON.stringify({provider:'bandcamp',item_id:String(songId),endpoint_id:sel.value})})}
function renderPodcastFeeds(items){let box=document.getElementById('podcasts');box.innerHTML='';for(const f of items){let row=document.createElement('div');row.style.marginTop='10px';row.innerHTML=`<div class="row"><b>${esc(f.name)}</b><code>${esc(f.url)}</code><button class="episodes">Episodes</button><button class="remove">Remove</button></div><div id="pod-eps-${esc(f.id)}"></div>`;row.querySelector('.episodes').onclick=()=>loadPodcastEpisodes(f.id);row.querySelector('.remove').onclick=()=>removePodcast(f.id);box.appendChild(row)}}
async function addPodcast(){let name=document.getElementById('podName').value.trim(),url=document.getElementById('podUrl').value.trim();if(!url)return;let d=await api('/api/v1/providers/podcasts',{method:'POST',body:JSON.stringify({name:name||null,url})});renderPodcastFeeds(d.podcast_feeds);document.getElementById('podName').value='';document.getElementById('podUrl').value=''}
async function removePodcast(id){let d=await api('/api/v1/providers/podcasts/'+encodeURIComponent(id),{method:'DELETE'});renderPodcastFeeds(d.podcast_feeds)}
async function loadPodcastEpisodes(id){let box=document.getElementById('pod-eps-'+id);box.textContent='Loading episodes…';try{let d=await api('/api/v1/providers/podcasts/'+encodeURIComponent(id)+'/episodes');box.innerHTML='';for(const ep of d.episodes||[]){let row=document.createElement('div');row.className='row';row.style.marginTop='6px';row.innerHTML=`<span>${esc(ep.title)}</span><span class="muted">${esc(ep.published||'')}</span><select>${endpointOptions()}</select><button>Play</button>`;let sel=row.querySelector('select');row.querySelector('button').onclick=()=>playPodcast(id,ep.id,sel);box.appendChild(row)}}catch(e){box.textContent='Podcast load failed: '+e.message}}
async function playPodcast(feedId,episodeId,sel){if(!sel.value){alert('No playable endpoint is registered');return}await api('/api/v1/streaming/play',{method:'POST',body:JSON.stringify({provider:'podcasts',item_id:feedId+':'+episodeId,endpoint_id:sel.value})})}

function renderStations(items){let box=document.getElementById('stations');box.innerHTML='';let opts=endpointOptions();for(const s of items){let d=document.createElement('div');d.className='row';d.style.marginTop='10px';d.innerHTML=`<b>${s.name}</b><code>${s.url}</code><select id="ep-${s.id}">${opts}</select><button class="play">Play</button><button class="stop">Stop</button><button class="remove">Remove</button>`;d.querySelector('.play').onclick=()=>playStation(s.id);d.querySelector('.stop').onclick=()=>stopStation(s.id);d.querySelector('.remove').onclick=()=>removeStation(s.id);box.appendChild(d)}}
async function addStation(){let name=document.getElementById('stationName').value.trim(),url=document.getElementById('stationUrl').value.trim();if(!name||!url)return;let d=await api('/api/v1/streaming/radio',{method:'POST',body:JSON.stringify({name,url})});renderStations(d.radio_stations);document.getElementById('stationName').value='';document.getElementById('stationUrl').value=''}
async function playStation(id){let ep=document.getElementById('ep-'+id);if(!ep||!ep.value){alert('No playable SurroundCore endpoint is registered');return}await api('/api/v1/streaming/play',{method:'POST',body:JSON.stringify({provider:'internet_radio',item_id:id,endpoint_id:ep.value})})}
async function stopStation(id){let ep=document.getElementById('ep-'+id);if(!ep||!ep.value)return;await api('/api/v1/playback/'+encodeURIComponent(ep.value)+'/stop',{method:'POST'})}
async function removeStation(id){let d=await api('/api/v1/streaming/radio/'+encodeURIComponent(id),{method:'DELETE'});renderStations(d.radio_stations)}
hashToken();if(TOKEN){document.getElementById('token').value=TOKEN;connect()}
</script></main></body></html>''')
    return ''.join(parts)
